version: '3.8'

services:
  faucet-api:
    build: .
    container_name: rpk-faucet-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RPK_STELLAR
      - ADMIN_STELLAR
      - SEPOLIA_PRIVATE_KEY
      - SEPOLIA_CONTRACT_ADDRESS
      - RPK_SEPOLIA
      - ADMIN_SEPOLIA
    restart: unless-stopped
